import { useContext, useState } from "react";
import { Button } from "../components/UI";
import { navigate } from "../router/router";
import { BoardContext } from "../store/BoardContext";

export function HomePage() {
  const { isInviteValid, recentMeetings } = useContext(BoardContext); const [code, setCode] = useState(""); const [error, setError] = useState("");
  const join = () => { const value = code.trim().toUpperCase(); if (!value) return setError("초대 코드나 링크를 입력해 주세요."); const parsed = value.includes("/JOIN/") ? value.split("/JOIN/").pop() : value; if (!isInviteValid(parsed)) return setError("존재하지 않거나 만료된 초대예요."); navigate(`/join/${parsed}`); };
  return <main className="flex min-h-screen items-center justify-center px-4 py-10"><section className="w-full max-w-md text-center"><p className="mb-3 text-xs font-bold tracking-[.25em] text-coral">연당</p><h1 className="text-3xl font-bold leading-tight">가고 싶은 곳,<br />친구들과 <span className="text-coral">함께</span> 모아요</h1><p className="mt-3 text-sm text-ink-2">한 모임에 장소를 모아 지도에서 비교하고 함께 골라요.</p><Button className="mt-7" onClick={() => navigate("/boards/new")}>＋ 새 모임 만들기</Button><div className="my-5 flex items-center gap-2 text-xs text-ink-3"><i className="h-px flex-1 bg-line" />초대 코드로 입장<i className="h-px flex-1 bg-line" /></div><div className="flex gap-2 rounded-2xl border border-line bg-white p-2"><input value={code} onChange={(e) => { setCode(e.target.value); setError(""); }} className="min-w-0 flex-1 px-3 font-bold outline-none" placeholder="예: A7K-92" /><Button variant="navy" className="!w-auto !px-4 !py-3" onClick={join}>입장</Button></div>{error && <p className="mt-2 text-left text-sm text-coral">{error}</p>}<div className="mt-8 text-left"><h2 className="mb-3 font-bold">최근 참여한 모임</h2>{recentMeetings.length ? recentMeetings.map((meeting) => <button key={meeting.id} type="button" onClick={() => navigate(`/boards/${meeting.id}`)} className="mb-2 flex w-full items-center justify-between rounded-2xl border border-line bg-white p-4 text-left"><span><b className="block">{meeting.name}</b><small className="text-ink-2">초대 코드 {meeting.inviteCode}</small></span><span>→</span></button>) : <p className="rounded-2xl bg-white p-4 text-sm text-ink-2">최근 참여한 모임이 없어요.</p>}</div></section></main>;
}
